# Generated by Django 5.1.2 on 2024-10-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0002_alter_state_state_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('sms', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('discord', models.CharField(blank=True, max_length=30, null=True)),
                ('instagram', models.CharField(blank=True, max_length=30, null=True)),
                ('snapchat', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('not_verified', 'Not Verified'), ('verified', 'Verified')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('sms', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('discord', models.CharField(blank=True, max_length=30, null=True)),
                ('instagram', models.CharField(blank=True, max_length=30, null=True)),
                ('snapchat', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('not_verified', 'Not Verified'), ('verified', 'Verified')], max_length=20)),
                ('states', models.ManyToManyField(to='auth_app.state')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
