# Generated by Django 5.1.2 on 2024-10-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('not_verified', 'Not Verified'), ('verified', 'Verified')], default='in_progress', max_length=20),
        ),
    ]
