# Generated by Django 5.1.2 on 2024-10-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_notes_lead_username_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('not_verified', 'Not Verified'), ('verified', 'Verified')], default='in_progress', max_length=20),
        ),
    ]
