# Generated by Django 5.1.3 on 2024-11-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_shipping_notes_alter_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
