# Generated by Django 5.1.3 on 2024-11-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_user_id_alter_shipping_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='discord',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='instagram',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='snapchat',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='discord',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='instagram',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='snapchat',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
