# Generated by Django 5.1.3 on 2024-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_discord_alter_lead_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
