# Generated by Django 5.1.2 on 2024-10-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
