# Generated by Django 5.1.2 on 2024-10-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.CharField(choices=[(True, 'true'), (False, 'false')], default=False, max_length=10),
        ),
    ]
