# Generated by Django 5.1.2 on 2024-10-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_id', models.CharField(max_length=50, unique=True)),
                ('telegram_username', models.CharField(max_length=50)),
                ('bot_father_token', models.CharField(max_length=255)),
                ('bot_url', models.CharField(max_length=255)),
                ('server_username', models.CharField(blank=True, max_length=255)),
                ('server_password', models.CharField(blank=True, max_length=255)),
                ('instance_dns', models.CharField(blank=True, max_length=255)),
                ('instance_username', models.CharField(blank=True, max_length=255)),
                ('instance_password', models.CharField(blank=True, max_length=255)),
                ('database_backup', models.FileField(blank=True, null=True, upload_to='backup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
