# Generated by Django 5.1.2 on 2024-10-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_timezone',
            field=models.CharField(default='Asia/Karachi', max_length=50),
        ),
    ]
