# Generated by Django 5.1.2 on 2024-10-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agentprofile',
            table='agent_profile',
        ),
    ]
