# Generated by Django 5.1.3 on 2024-11-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_agentprofile_uan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='channel_id',
            field=models.CharField(max_length=100),
        ),
    ]
